### ISSUE TITLE
PHP Parse error:  syntax error, unexpected identifier "SECRET", expecting ")" in ./encryption-recovery-tools-master/server-side-encryption/recover.php on line 182

### ISSUE THREAD

**Issue by IsmaStifler** [nextcloud/encryption-recovery-tools#27] opened 2023-10-30 22:23 UTC
Hello, I am not understanding anything about this syntax problem that jumps

`// ===== USER CONFIGURATION =====

	// nextcloud definitions - you can get these values from `config/config.php`
	config("DATADIRECTORY", "E:\data\");
	config("SECRET", "pMrthvv8msrgFy6d8ywf0aokniqqvKzJY5Eso/eVdJPM6w1t");

	// instanceid definition
	config("INSTANCEID", "ociywakfr04w");

	// recovery password definition
	// config("RECOVERY_PASSWORD", "");

	// user password definition,
	// replace "username" with the actual usernames and "password" with the actual passwords,
	// you can add or remove entries as necessary
	// config("USER_PASSWORDS", ["username" => "password",
	//                           "username" => "password",
	//                           "username" => "password"]);

	// external storage definition,
	// replace "storage" with the actual external storage names and "/mountpath" with the actual external storage mount paths,
	// you can add or remove entries as necessary
	// config("EXTERNAL_STORAGES", ["storage" => "/mountpath",
	//                              "storage" => "/mountpath",
	//                              "storage" => "/mountpath"]);

	// missing headers definition,
	// this should only be set to TRUE if you have really old encrypted files that do not contain encryption headers,
	// in most cases this will rather break unencrypted files that may live alongside your encrypted files
	// config("SUPPORT_MISSING_HEADERS", false);

	// debug mode definitions
	// config("DEBUG_MODE",         false);
	// config("DEBUG_MODE_VERBOSE", false);
`

PHP Parse error:  syntax error, unexpected identifier "SECRET", expecting ")" in /mnt/c/Users/ismai/Desktop/encryption-recovery-tools-master/server-side-encryption/recover.php on line 182

**Comment by yahesh** [comment] 2023-10-30 22:56
@IsmaStifler The problem is that `"E:\data\"` is not a valid PHP string. The backslash is an escape character which leads to the trailing quotes becoming part of the string instead of terminating the string.

As I see you are using Windows, which is not supported. The readme states the following:

```
Windows users: This script will not run on Windows. Please use the Windows Subsystem for Linux instead.
```

I will close this issue as **won't fix**.

**Closed by yahesh** 2023-10-30 22:56 UTC
Labels: wontfix, individual problem

**Comment by IsmaStifler** [comment] 2023-10-30 23:03
yes, i have installed ubuntu in windows


![image](https://github.com/nextcloud/encryption-recovery-tools/assets/19431908/17436bcb-3d95-4811-a09b-d4adead83770)

**Comment by IsmaStifler** [comment] 2023-10-30 23:05
![image](https://github.com/nextcloud/encryption-recovery-tools/assets/19431908/841689f1-811e-424e-a40a-1f44fac030de)

**Comment by IsmaStifler** [comment] 2023-10-30 23:08
Exactly what would I need to do? I created a Linux virtual one, and could I find the data in SMB?

**Comment by IsmaStifler** [comment] 2023-10-30 23:09
![image](https://github.com/nextcloud/encryption-recovery-tools/assets/19431908/40e33cb1-946f-4cf7-b3ac-2e6b87676553)

**Comment by yahesh** [comment] 2023-10-30 23:11
@IsmaStifler You tried to set `"E:\data\"` as the `DATADIRECTORY` when it should be `"/mnt/e/data/"` instead.

**Comment by IsmaStifler** [comment] 2023-10-30 23:11
I really don't know how to put that directory


yes mb 


I realized as soon as you told me I'm going to try it

thank you

**Comment by IsmaStifler** [comment] 2023-10-30 23:14
ops...


![image](https://github.com/nextcloud/encryption-recovery-tools/assets/19431908/c9a1e9b7-e9b4-4419-807e-40e299aee097)

**Comment by yahesh** [comment] 2023-10-30 23:18
Please just remove the second parameter in square brackets. This parameter is meant to select specific files to decrypt which you don’t want at the moment. Am 31.10.2023 um 00:15 schrieb IsmaStifler ***@***.***>:﻿
ops...

**Comment by IsmaStifler** [comment] 2023-10-30 23:20
Yes, I had a syntax problem in recover and now it stays like this, I understand, it worked!!!


My mistakes

![image](https://github.com/nextcloud/encryption-recovery-tools/assets/19431908/cee4aaa4-2f68-4116-9a45-6a191cc8c4bc)

**Comment by yahesh** [comment] 2023-10-30 23:23
It will start to show which files it already worked on when it finished preparing the file structure.

**Comment by IsmaStifler** [comment] 2023-10-30 23:26
perfect thx ^^
